In [5]:
import os
import json
from pathlib import Path
from datetime import datetime, timedelta
import pandas as pd
from dotenv import load_dotenv
from eptr2 import EPTR2

In [6]:
env_path = next((path / '.env' for path in [Path.cwd(), *Path.cwd().parents] if (path / '.env').exists()), None)

if env_path is None:
    raise FileNotFoundError('.env dosyası bulunamadı.')

load_dotenv(env_path)
username = os.getenv("EPIAS_USERNAME") or os.getenv("EPTR_USERNAME")
password = os.getenv("EPIAS_PASSWORD") or os.getenv("EPTR_PASSWORD")

if not username or not password:
    raise ValueError('EPIAS_USERNAME veya EPIAS_PASSWORD .env içinde eksik.')

In [7]:
eptr = EPTR2(username=username, password=password, dotenv_path=str(env_path))

In [8]:
# 1. Yük Tahmin Planı (ytp_mwh) - consumption modülü altındadır:
res_ytp = eptr.call(
    "load-plan",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()
res_ytp

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'time': {0: '00:00',
  1: '01:00',
  2: '02:00',
  3: '03:00',
  4: '04:00',
  5: '05:00',
  6: '06:00',
  7: '07:00',
  8: '08:00',
  9: '09:00',
  10: '10:00',
  11: '11:00',
  12: '12:00',
  13: '13:00',
  14: '14:00',
  15: '15:00',
  16: '16:00',
  17: '17:00',
  18: '18:00',
  19: '19:00',
  20: '20:00',
  21: '21:00',
  22: '22:00',
  23: '23:00'},
 'lep': {0: 47723,
  1: 45286,
  2: 43177,
  3: 41884,
  4: 40978,
  5: 40244,
  6: 40272,
  7: 43077,
  8: 49053,
  9: 52242,
  10: 54215,
  11: 55602,
  12: 55414,
  13: 56376,
  14: 56997,
  15: 56322,
  16: 55391,
  17: 54322,
  18: 53514,
  19: 53775,
  20: 54717,
  21: 54193,
  22: 52645,
  23: 50303}}

In [9]:
# KGUP
res_kgup = eptr.call(
    "kgup",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()
res_kgup

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'time': {0: '00:00',
  1: '01:00',
  2: '02:00',
  3: '03:00',
  4: '04:00',
  5: '05:00',
  6: '06:00',
  7: '07:00',
  8: '08:00',
  9: '09:00',
  10: '10:00',
  11: '11:00',
  12: '12:00',
  13: '13:00',
  14: '14:00',
  15: '15:00',
  16: '16:00',
  17: '17:00',
  18: '18:00',
  19: '19:00',
  20: '20:00',
  21: '21:00',
  22: '22:00',
  23: '23:00'},
 'toplam': {0: 44872.96,
  1: 42236.25,
  2: 40218.84,
  3: 39095.48,
  4: 37989.67,
  5: 36950.14,
  6: 36544.8,
  7: 39172.57,
  8: 45582.14,
  9: 49723.72,
  10: 52046.09,
  11: 53590.74,
  12: 53176.26,
  13: 54307.11,
  14: 55494.71,
  15: 55031.33,
  16: 54808.13,
  17: 53425.66,
  18: 52011.22,
  19: 50970.16,
  20: 51589.63,
  21: 50497.99,
  22: 49493.46,
  23: 47819.95},
 'dogalgaz': {0: 9619.25,
  1: 8806.64,
  2: 8415.84,
  3: 8380.14,
  4: 8112.15,
  5: 7315.74,
  6: 5935.85,
  7: 5189.39,
  8: 5473.04,
  9: 5663.44,
  10: 5382.42,
  11: 5859.97,
  12: 5202.05,
  13: 5880.64,
  14: 7381.0,
  15: 7637.88,
  16: 8918.52,
  17: 10602.37,
  18: 12179.02,
  19: 12537.2,
  20: 12006.02,
  21: 11112.56,
  22: 11652.61,
  23: 10574.36},
 'ruzgar': {0: 5014.37,
  1: 4600.2,
  2: 4324.62,
  3: 4101.64,
  4: 3882.5,
  5: 3665.12,
  6: 3405.79,
  7: 3115.1,
  8: 2901.51,
  9: 2808.0,
  10: 2772.65,
  11: 2780.59,
  12: 2808.71,
  13: 2896.77,
  14: 3133.88,
  15: 3415.16,
  16: 3687.01,
  17: 4047.69,
  18: 4224.97,
  19: 4642.69,
  20: 5140.48,
  21: 5314.57,
  22: 5169.82,
  23: 5284.45},
 'linyit': {0: 4614.0,
  1: 4617.0,
  2: 4592.0,
  3: 4546.0,
  4: 4577.0,
  5: 4580.0,
  6: 4578.29,
  7: 4531.2,
  8: 4592.9,
  9: 4639.4,
  10: 4680.0,
  11: 4713.3,
  12: 4749.59,
  13: 4709.1,
  14: 4724.5,
  15: 4723.4,
  16: 4747.9,
  17: 4734.2,
  18: 4794.7,
  19: 4850.6,
  20: 4882.6,
  21: 4910.2,
  22: 4922.0,
  23: 5072.0},
 'tasKomur': {0: 269,
  1: 269,
  2: 269,
  3: 269,
  4: 269,
  5: 269,
  6: 269,
  7: 269,
  8: 269,
  9: 269,
  10: 269,
  11: 158,
  12: 140,
  13: 140,
  14: 140,
  15: 140,
  16: 140,
  17: 140,
  18: 140,
  19: 140,
  20: 140,
  21: 140,
  22: 140,
  23: 140},
 'ithalKomur': {0: 9281.5,
  1: 9279.5,
  2: 9281.5,
  3: 9224.5,
  4: 9224.5,
  5: 9224.5,
  6: 9225.5,
  7: 8983.5,
  8: 9046.5,
  9: 8852.5,
  10: 8860.5,
  11: 8881.5,
  12: 8824.5,
  13: 9096.5,
  14: 9095.5,
  15: 9189.5,
  16: 9245.5,
  17: 9231.5,
  18: 9284.5,
  19: 9281.5,
  20: 9281.5,
  21: 9281.5,
  22: 9281.5,
  23: 9281.5},
 'fuelOil': {0: 2.2,
  1: 2.2,
  2: 2.2,
  3: 2.2,
  4: 2.2,
  5: 2.2,
  6: 2.2,
  7: 2.2,
  8: 2.8,
  9: 3.6,
  10: 4.1,
  11: 4.7,
  12: 4.7,
  13: 4.2,
  14: 3.4,
  15: 2.7,
  16: 2.2,
  17: 2.2,
  18: 2.2,
  19: 2.2,
  20: 2.2,
  21: 2.2,
  22: 2.2,
  23: 2.2},
 'jeotermal': {0: 808.58,
  1: 823.7,
  2: 837.96,
  3: 852.57,
  4: 868.42,
  5: 879.33,
  6: 884.89,
  7: 880.51,
  8: 858.17,
  9: 834.02,
  10: 812.68,
  11: 781.61,
  12: 754.08,
  13: 730.15,
  14: 710.4,
  15: 695.47,
  16: 681.71,
  17: 678.8,
  18: 679.91,
  19: 691.72,
  20: 711.77,
  21: 742.83,
  22: 770.98,
  23: 789.59},
 'barajli': {0: 11826.52,
  1: 10460.15,
  2: 9233.45,
  3: 8524.45,
  4: 7862.45,
  5: 7669.95,
  6: 7309.75,
  7: 7369.74,
  8: 8654.15,
  9: 8684.87,
  10: 8595.03,
  11: 8306.27,
  12: 8300.97,
  13: 8600.69,
  14: 9074.03,
  15: 10157.95,
  16: 11594.78,
  17: 12414.86,
  18: 13669.13,
  19: 14240.64,
  20: 15072.92,
  21: 14791.45,
  22: 13759.75,
  23: 13064.75},
 'nafta': {0: 0,
  1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0},
 'biokutle': {0: 898.69,
  1: 897.15,
  2: 896.98,
  3: 899.39,
  4: 899.44,
  5: 896.02,
  6: 899.59,
  7: 921.44,
  8: 962.3,
  9: 981.71,
  10: 988.85,
  11: 991.54,
  12: 996.7,
  13: 988.89,
  14: 982.31,
  15: 986.58,
  16: 961.21,
  17: 935.72,
  18: 917.55,
  19: 897.02,
  20: 897.15,
  21: 902.1,
  22: 904.16,
  23: 905.58},
 'akarsu': {0: 2291.92,
  1: 2233.91,
  2: 2117.54,
  3: 2044.31,
  4: 2058.85,
  5: 2081.4,
  6: 2065.16,
  7: 1781.37,
  8: 1938.03,
  9: 1978.08,
  10: 1933.52,
  11: 1923.82,
  12: 1724.95,
  13: 1888.15,
  14: 1941.39,
  15: 1834.41,
  16: 1912.07,
  17: 2153.94,
  18: 2318.45,
  19: 2796.32,
  20: 3097.81,
  21: 3000.59,
  22: 2638.01,
  23: 2454.07},
 'gunes': {0: 29.28,
  1: 29.14,
  2: 30.09,
  3: 33.62,
  4: 45.8,
  5: 185.6,
  6: 1784.43,
  7: 5948.98,
  8: 10691.61,
  9: 14805.34,
  10: 17537.03,
  11: 18977.58,
  12: 19449.48,
  13: 19151.57,
  14: 18090.38,
  15: 16011.47,
  16: 12679.59,
  17: 8258.42,
  18: 3584.75,
  19: 668.73,
  20: 137.07,
  21: 79.66,
  22: 34.8,
  23: 33.81},
 'diger': {0: 217.65,
  1: 217.66,
  2: 217.66,
  3: 217.66,
  4: 187.36,
  5: 181.28,
  6: 184.35,
  7: 180.14,
  8: 192.13,
  9: 203.76,
  10: 210.31,
  11: 211.86,
  12: 220.53,
  13: 220.45,
  14: 217.92,
  15: 236.81,
  16: 237.64,
  17: 225.96,
  18: 216.04,
  19: 221.54,
  20: 220.11,
  21: 220.33,
  22: 217.63,
  23: 217.64}}

In [10]:
# 3. PTF
eptr = EPTR2(username=username, password=password, dotenv_path=str(env_path))
res_ptf = eptr.call(
    "mcp",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()
res_ptf

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'hour': {0: '00:00',
  1: '01:00',
  2: '02:00',
  3: '03:00',
  4: '04:00',
  5: '05:00',
  6: '06:00',
  7: '07:00',
  8: '08:00',
  9: '09:00',
  10: '10:00',
  11: '11:00',
  12: '12:00',
  13: '13:00',
  14: '14:00',
  15: '15:00',
  16: '16:00',
  17: '17:00',
  18: '18:00',
  19: '19:00',
  20: '20:00',
  21: '21:00',
  22: '22:00',
  23: '23:00'},
 'price': {0: 3891.45,
  1: 3602.0,
  2: 2993.0,
  3: 3449.01,
  4: 3484.15,
  5: 3555.0,
  6: 3963.5,
  7: 2117.71,
  8: 3739.15,
  9: 3795.0,
  10: 3250.0,
  11: 3449.01,
  12: 2699.0,
  13: 3300.01,
  14: 3600.0,
  15: 3083.01,
  16: 3599.99,
  17: 3900.01,
  18: 3915.27,
  19: 4499.67,
  20: 4500.0,
  21: 4500.0,
  22: 4099.99,
  23: 3600.0},
 'priceUsd': {0: 82.63,
  1: 76.49,
  2: 63.55,
  3: 73.24,
  4: 73.98,
  5: 75.49,
  6: 84.16,
  7: 44.97,
  8: 79.4,
  9: 80.58,
  10: 69.01,
  11: 73.24,
  12: 57.31,
  13: 70.07,
  14: 76.44,
  15: 65.47,
  16: 76.44,
  17: 82.81,
  18: 83.14,
  19: 95.55,
  20: 95.55,
  21: 95.55,
  22: 87.06,
  23: 76.44},
 'priceEur': {0: 72.26,
  1: 66.89,
  2: 55.58,
  3: 64.05,
  4: 64.7,
  5: 66.01,
  6: 73.6,
  7: 39.33,
  8: 69.43,
  9: 70.47,
  10: 60.35,
  11: 64.05,
  12: 50.12,
  13: 61.28,
  14: 66.85,
  15: 57.25,
  16: 66.85,
  17: 72.42,
  18: 72.71,
  19: 83.56,
  20: 83.56,
  21: 83.56,
  22: 76.14,
  23: 66.85}}

In [11]:
# 4. SMF
res_smf = eptr.call(
    "smp",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()

res_smf

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'hour': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'systemMarginalPrice': {0: 3891.45,
  1: 3602.0,
  2: 3450.0,
  3: 3500.0,
  4: 3902.0,
  5: 3557.0,
  6: 3965.0,
  7: 2117.71,
  8: 3740.0,
  9: 3797.0,
  10: 3250.0,
  11: 3450.0,
  12: 1000.0,
  13: 2882.0,
  14: 3638.0,
  15: 3550.0,
  16: 4180.0,
  17: 4497.6,
  18: 3915.27,
  19: 4499.78,
  20: 4500.0,
  21: 4500.0,
  22: 3033.0,
  23: 3452.0}}

In [12]:
# Teklif Edilen Alış Miktarı
res_dem_offer = eptr.call(
    "dam-bid", 
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T23:59:00+03:00"
)
res_dem_offer

                         date   hour  bidQuantity
0   2026-07-22T00:00:00+03:00  00:00      29239.6
1   2026-07-22T01:00:00+03:00  01:00      28124.6
2   2026-07-22T02:00:00+03:00  02:00      27219.3
3   2026-07-22T03:00:00+03:00  03:00      26695.4
4   2026-07-22T04:00:00+03:00  04:00      26457.1
5   2026-07-22T05:00:00+03:00  05:00      26139.5
6   2026-07-22T06:00:00+03:00  06:00      26245.5
7   2026-07-22T07:00:00+03:00  07:00      25970.8
8   2026-07-22T08:00:00+03:00  08:00      29055.0
9   2026-07-22T09:00:00+03:00  09:00      30379.0
10  2026-07-22T10:00:00+03:00  10:00      30498.6
11  2026-07-22T11:00:00+03:00  11:00      30842.8
12  2026-07-22T12:00:00+03:00  12:00      29223.3
13  2026-07-22T13:00:00+03:00  13:00      30272.3
14  2026-07-22T14:00:00+03:00  14:00      31528.1
15  2026-07-22T15:00:00+03:00  15:00      32648.1
16  2026-07-22T16:00:00+03:00  16:00      33424.3
17  2026-07-22T17:00:00+03:00  17:00      34549.6
18  2026-07-22T18:00:00+03:00  18:00      34722.5
19  2026-07-22T19:00:00+03:00  19:00      35695.5
20  2026-07-22T20:00:00+03:00  20:00      35919.4
21  2026-07-22T21:00:00+03:00  21:00      35438.4
22  2026-07-22T22:00:00+03:00  22:00      32612.6
23  2026-07-22T23:00:00+03:00  23:00      31016.2

In [13]:
# Teklif Edilen Satış Miktarı
res_sup_offer = eptr.call(
    "dam-offer", 
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T23:59:00+03:00"
)
res_sup_offer

                         date   hour  offerQuantity
0   2026-07-22T00:00:00+03:00  00:00        30647.7
1   2026-07-22T01:00:00+03:00  01:00        30086.1
2   2026-07-22T02:00:00+03:00  02:00        29972.7
3   2026-07-22T03:00:00+03:00  03:00        29585.6
4   2026-07-22T04:00:00+03:00  04:00        29220.6
5   2026-07-22T05:00:00+03:00  05:00        28916.7
6   2026-07-22T06:00:00+03:00  06:00        30188.0
7   2026-07-22T07:00:00+03:00  07:00        31771.3
8   2026-07-22T08:00:00+03:00  08:00        33501.2
9   2026-07-22T09:00:00+03:00  09:00        35284.5
10  2026-07-22T10:00:00+03:00  10:00        36013.5
11  2026-07-22T11:00:00+03:00  11:00        35083.1
12  2026-07-22T12:00:00+03:00  12:00        34565.4
13  2026-07-22T13:00:00+03:00  13:00        34577.5
14  2026-07-22T14:00:00+03:00  14:00        34780.3
15  2026-07-22T15:00:00+03:00  15:00        36109.5
16  2026-07-22T16:00:00+03:00  16:00        35778.5
17  2026-07-22T17:00:00+03:00  17:00        35449.3
18  2026-07-22T18:00:00+03:00  18:00        34780.0
19  2026-07-22T19:00:00+03:00  19:00        34185.5
20  2026-07-22T20:00:00+03:00  20:00        33312.1
21  2026-07-22T21:00:00+03:00  21:00        32580.3
22  2026-07-22T22:00:00+03:00  22:00        31997.3
23  2026-07-22T23:00:00+03:00  23:00        31694.6

In [18]:
# Gerçekleşen Üretim
res_gen = eptr.call(
    "rt-gen",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
)
res_gen

,date,hour,total,naturalGas,dammedHydro,lignite,river,importCoal,wind,sun,fueloil,geothermal,asphaltiteCoal,blackCoal,biomass,naphta,lng,importExport,wasteheat
0,2026-07-22T00:00:00+03:00,00:00,47190.69,10168.19,11820.14,5233.61,2335.23,9946.84,4823.60,1.17,86.90,1021.74,183.25,518.10,890.90,0,0,77.54,83.48
1,2026-07-22T01:00:00+03:00,01:00,44701.72,9237.51,10697.30,5245.55,2267.47,9942.34,4397.03,1.17,86.26,1040.07,178.84,519.45,888.50,0,0,116.81,83.42
2,2026-07-22T02:00:00+03:00,02:00,42977.70,9226.37,9423.81,5211.98,2143.84,9948.94,4094.15,1.21,85.66,1059.83,183.25,546.79,892.46,0,0,73.01,86.40
3,2026-07-22T03:00:00+03:00,03:00,41655.32,9121.38,8662.47,5190.04,2088.98,9912.54,3851.64,1.51,85.57,1078.05,183.25,566.79,902.61,0,0,-74.36,84.85
4,2026-07-22T04:00:00+03:00,04:00,40584.76,8806.56,8119.70,5188.74,2103.39,9908.22,3632.13,1.71,85.51,1091.34,183.25,566.97,892.07,0,0,-80.37,85.54
5,2026-07-22T05:00:00+03:00,05:00,39618.00,8308.75,7779.22,5203.58,2102.84,9907.46,3442.30,34.35,89.76,1091.83,181.05,573.16,893.23,0,0,-73.79,84.26
6,2026-07-22T06:00:00+03:00,06:00,38023.73,6950.37,7389.32,5181.74,2104.99,9891.14,3247.91,567.43,82.47,1124.81,181.04,580.22,883.51,0,0,-248.25,87.03
7,2026-07-22T07:00:00+03:00,07:00,37301.87,6037.69,7232.81,5158.31,1774.96,9636.79,2908.00,1917.70,76.62,1107.07,185.46,573.90,875.90,0,0,-271.45,88.11
8,2026-07-22T08:00:00+03:00,08:00,40180.54,6779.19,8527.60,5220.75,1898.70,9707.40,2447.14,2940.75,88.97,1083.97,183.24,570.67,865.68,0,0,-217.85,84.33
9,2026-07-22T09:00:00+03:00,09:00,40125.39,7134.49,8275.38,5282.96,1877.93,9332.24,2164.07,3460.35,88.45,1044.71,181.05,576.38,864.32,0,0,-236.82,79.88
10,2026-07-22T10:00:00+03:00,10:00,39412.02,6535.36,8427.57,5314.87,1809.15,9023.14,1915.51,3742.50,88.27,1001.50,181.04,580.74,863.64,0,0,-151.16,79.89
11,2026-07-22T11:00:00+03:00,11:00,39516.18,6915.96,8048.77,5300.70,1795.71,9165.09,1897.31,3928.56,81.70,958.76,185.46,454.74,864.46,0,0,-159.51,78.47
12,2026-07-22T12:00:00+03:00,12:00,38324.68,6426.15,8000.26,5263.57,1650.70,8687.42,1970.26,3938.61,88.27,944.55,181.04,440.77,853.74,0,0,-199.85,79.19
13,2026-07-22T13:00:00+03:00,13:00,40069.77,7144.89,8334.91,5302.21,1702.72,9113.77,2150.89,3924.45,87.87,926.48,185.46,429.67,841.80,0,0,-154.73,79.38
14,2026-07-22T14:00:00+03:00,14:00,42553.82,8249.37,8825.95,5298.44,1805.22,9689.20,2424.30,3811.28,86.44,912.66,183.25,423.33,846.67,0,0,-80.50,78.21
15,2026-07-22T15:00:00+03:00,15:00,44300.40,8609.27,9904.21,5272.46,1758.97,9854.04,2731.73,3464.81,85.67,881.31,183.25,421.99,836.29,0,0,220.78,75.62
16,2026-07-22T16:00:00+03:00,16:00,46926.06,9109.02,11690.51,5284.16,1894.93,9902.73,3123.47,3173.31,86.65,897.63,181.04,418.75,831.76,0,0,253.58,78.52
17,2026-07-22T17:00:00+03:00,17:00,50056.37,10706.01,13408.80,5338.49,2168.27,9886.91,3696.65,2425.54,87.42,900.32,178.84,405.20,842.22,0,0,-68.50,80.20
18,2026-07-22T18:00:00+03:00,18:00,51679.42,12464.62,13610.21,5456.59,2349.61,9953.76,4452.02,1104.78,88.30,915.79,185.46,402.06,846.43,0,0,-228.76,78.55
19,2026-07-22T19:00:00+03:00,19:00,53183.61,12855.08,14446.80,5548.87,2803.88,9942.24,4997.83,162.48,99.71,945.75,183.25,403.00,858.79,0,0,-146.02,81.95
20,2026-07-22T20:00:00+03:00,20:00,54285.17,12384.36,15388.55,5594.23,3086.52,9957.62,5444.20,23.98,100.63,972.70,183.25,401.40,864.25,0,0,-194.21,77.69
21,2026-07-22T21:00:00+03:00,21:00,54174.30,12346.56,14842.67,5510.86,3054.18,9944.73,6034.19,7.08,102.14,996.78,181.04,380.32,862.71,0,0,-166.48,77.52
22,2026-07-22T22:00:00+03:00,22:00,52268.90,12124.23,13473.70,5569.33,2649.84,9961.35,6012.00,0.11,102.73,1016.90,181.04,390.11,882.34,0,0,-177.63,82.85
23,2026-07-22T23:00:00+03:00,23:00,50488.24,11342.28,12966.87,5539.49,2420.57,9951.94,5573.92,0.10,87.06,1035.68,183.25,388.05,865.42,0,0,48.70,84.91

In [17]:
# Gerçekleşen Tüketim
res_cons = eptr.call(
    "rt-cons",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
)
res_cons

                         date   time  consumption
0   2026-07-22T00:00:00+03:00  00:00     47238.37
1   2026-07-22T01:00:00+03:00  01:00     44742.48
2   2026-07-22T02:00:00+03:00  02:00     43012.58
3   2026-07-22T03:00:00+03:00  03:00     41722.86
4   2026-07-22T04:00:00+03:00  04:00     40717.96
5   2026-07-22T05:00:00+03:00  05:00     40295.92
6   2026-07-22T06:00:00+03:00  06:00     40528.01
7   2026-07-22T07:00:00+03:00  07:00     43511.78
8   2026-07-22T08:00:00+03:00  08:00     50930.37
9   2026-07-22T09:00:00+03:00  09:00     54366.83
10  2026-07-22T10:00:00+03:00  10:00     55950.85
11  2026-07-22T11:00:00+03:00  11:00     57201.73
12  2026-07-22T12:00:00+03:00  12:00     56279.03
13  2026-07-22T13:00:00+03:00  13:00     57436.84
14  2026-07-22T14:00:00+03:00  14:00     58288.38
15  2026-07-22T15:00:00+03:00  15:00     57100.81
16  2026-07-22T16:00:00+03:00  16:00     55899.19
17  2026-07-22T17:00:00+03:00  17:00     54952.88
18  2026-07-22T18:00:00+03:00  18:00     53209.81
19  2026-07-22T19:00:00+03:00  19:00     53333.07
20  2026-07-22T20:00:00+03:00  20:00     54360.99
21  2026-07-22T21:00:00+03:00  21:00     54212.79
22  2026-07-22T22:00:00+03:00  22:00     52303.14
23  2026-07-22T23:00:00+03:00  23:00     50498.50

In [16]:
eptr.get_available_calls()

['dam-volume',
 'pi-offer',
 'pi-bid',
 'supply-demand',
 'dam-bid',
 'dam-offer',
 'dam-block-bid',
 'dam-block-offer',
 'dam-flexible-bid',
 'dam-flexible-offer',
 'dam-flexible-matching',
 'dam-clearing',
 'dam-clearing-org-list',
 'dam-diff',
 'wap',
 'idm-qty',
 'idm-mm-bid',
 'idm-mm-offer',
 'idm-mm-matching',
 'idm-volume',
 'idm-log',
 'idm-ob-qty',
 'smp',
 'smp-dir',
 'bpm-up',
 'bpm-down',
 'bi-long',
 'bi-short',
 'bi-euas',
 'imb-qty',
 'imb-vol',
 'imb-qty-g',
 'imb-org-list',
 'mcp',
 'interim-mcp',
 'interim-mcp-status',
 'mcp-smp-imb',
 'bpm-orders-w-avg',
 'bpm-orders',
 'kgup',
 'kgup-v1',
 'kudup',
 'eak',
 'rt-gen',
 'uevm',
 'pp-list',
 'pp-list-for-date-range',
 'uevm-pp-list',
 'gen-org',
 'region-list',
 'dpp-bulk',
 'rt-gen-bulk',
 'uevcb-list-bulk',
 'mms-message-type-list',
 'mms-region-list',
 'gen-uevcb',
 'lic-pp-list',
 'long-term-demand-forecast',
 'consumer-breakdown',
 'consumption-breakdown',
 'distribution-region-list',
 'load-plan',
 'rt-cons',
 'uecm',
 'st-uecm',
 'su-uecm',
 'anc-pf-qty',
 'anc-pfk',
 'anc-sf-qty',
 'anc-sfk',
 'wind-forecast',
 'ren-pp-list',
 'ren-rt-gen',
 'ren-uevm',
 'ren-ul-gen',
 'ren-ul-cost',
 'ren-lic-cost',
 'ren-income',
 'ren-total-cost',
 'ren-capacity',
 'ren-unit-cost',
 'ren-participant-list',
 'zero-balance',
 'iskk',
 'congestion-cost',
 'eic-x-org-list',
 'eic-w-org-list',
 'eic-w-uevcb-list',
 'international-line-events',
 'tcat-pre-year-forecast',
 'tcat-pre-month-forecast',
 'line-capacities',
 'capacity-demand',
 'nominal-capacity',
 'intl-direction-list',
 'intl-capacity-demand-direction-list',
 'mms',
 'mms-pp-list',
 'mms-uevcb-list',
 'district-list',
 'profile-group-list',
 'province-list',
 'date-init',
 'market-participants',
 'market-participants-organization-list',
 'participant-count-based-upon-license-type',
 'dams-active-fullness',
 'dams-daily-level',
 'dams-active-volume',
 'dams-daily-volume',
 'basin-list',
 'dam-list',
 'dams-level-minmax',
 'dams-volume-minmax',
 'dams-info',
 'dams-water-energy-provision',
 'idm-summary',
 'electricity-market-quantity',
 'idm-contract-list',
 'idm-order-history',
 'ra-distribution-list',
 'ra-organization-list',
 'ra-spg-list',
 'ra-vspg-list',
 'ra-meters',
 'ra-meter-volumes-period',
 'ra-meter-volumes-version',
 'ra-sum',
 'ng-participants',
 'ng-participant-list',
 'ng-balancing-notifications',
 'ng-balancing-price',
 'ng-bast',
 'ng-blue-code-ops',
 'ng-daily-match-qty',
 'ng-drp',
 'ng-daily-trade-volume',
 'ng-code-four-ops',
 'ng-gddk',
 'ng-green-code-ops',
 'ng-grp-match-qty',
 'ng-grp-trade-volume',
 'ng-imbalance-amount',
 'ng-imbalance-system',
 'ng-latest-settlement-date',
 'ng-match-quantity',
 'ng-orange-code-ops',
 'ng-physical-realization',
 'ng-spot-prices',
 'ng-shippers-imbalance-quantity',
 'ng-system-direction',
 'ng-total-trade-volume',
 'ng-transaction-history',
 'ng-virtual-realization',
 'ng-weekly-matched-quantity',
 'ng-wrp',
 'ng-weekly-trade-volume',
 'ng-vgp-contract-price-summary',
 'ng-vgp-contract-price-summary-period',
 'ng-vgp-contract-price-summary-se',
 'ng-vgp-delivery-period',
 'ng-vgp-delivery-year',
 'ng-vgp-ggf',
 'ng-vgp-ggf-period',
 'ng-vgp-ggf-se',
 'ng-vgp-matched-quantity',
 'ng-vgp-matched-quantity-period',
 'ng-vgp-matched-quantity-se',
 'ng-vgp-open-positions',
 'ng-vgp-open-positions-period',
 'ng-vgp-open-positions-se',
 'ng-vgp-order-book',
 'ng-vgp-transaction-history',
 'ng-vgp-transaction-history-period',
 'ng-vgp-transaction-history-se',
 'ng-vgp-transaction-volumes',
 'ng-vgp-transaction-volumes-period',
 'ng-vgp-transaction-volumes-se',
 'ng-tr-capacity-point',
 'ng-tr-daily-transmission',
 'ng-tr-day-ahead',
 'ng-tr-day-end',
 'ng-tr-entry-nomination',
 'ng-tr-exit-nomination',
 'ng-tr-max-entry-amount',
 'ng-tr-max-exit-amount',
 'ng-tr-actual-entry-amount',
 'ng-tr-actual-exit-amount',
 'ng-tr-reserved-entry-amount',
 'ng-tr-reserved-exit-amount',
 'ng-tr-stock-amount',
 'ng-tr-storage-facility-list',
 'ng-tr-bilateral-transfer',
 'menu',
 'page-settings',
 'yek-g-bilateral-contracts',
 'yek-g-redemptions',
 'yek-g-expirations',
 'yek-g-issued',
 'yek-g-order-quantity',
 'yek-g-match-price-minmax',
 'yek-g-trade-volume',
 'yek-g-wap',
 'yek-g-withdrawals',
 'yek-g-match-quantity',
 'vep-contract-price-summary',
 'vep-delivery-period-list',
 'vep-delivery-year-list',
 'vep-ggf',
 'vep-ggf-period',
 'vep-load-types',
 'vep-price-summaries',
 'vep-open-positions',
 'vep-trade-volume',
 'vep-transaction-history',
 'vep-transaction-history-periods',
 'vep-matching-quantity',
 'eligible-consumer-count-detail',
 'eligible-consumer-quantity',
 'get-distribution-companies',
 'main-tariff-group-list',
 'monthly-index',
 'multiple-factor',
 'mf-distribution',
 'mf-meter-reading-type',
 'mf-profile-group',
 'percentage-consumption-info',
 'planned-outages',
 'elig-profile-groups',
 'eligible-consumer-count',
 'unplanned-outages']