In [6]:
import os
import json
from pathlib import Path
from datetime import datetime, timedelta
import pandas as pd
from dotenv import load_dotenv
from eptr2 import EPTR2

In [7]:
env_path = next((path / '.env' for path in [Path.cwd(), *Path.cwd().parents] if (path / '.env').exists()), None)

if env_path is None:
    raise FileNotFoundError('.env dosyası bulunamadı.')

load_dotenv(env_path)
username = os.getenv("EPIAS_USERNAME") or os.getenv("EPTR_USERNAME")
password = os.getenv("EPIAS_PASSWORD") or os.getenv("EPTR_PASSWORD")

if not username or not password:
    raise ValueError('EPIAS_USERNAME veya EPIAS_PASSWORD .env içinde eksik.')

In [8]:
eptr = EPTR2(username=username, password=password, dotenv_path=str(env_path))

In [27]:
# 1. Yük Tahmin Planı (ytp_mwh) - consumption modülü altındadır:
res_ytp = eptr.call(
    "load-plan",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()
res_ytp

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'time': {0: '00:00',
  1: '01:00',
  2: '02:00',
  3: '03:00',
  4: '04:00',
  5: '05:00',
  6: '06:00',
  7: '07:00',
  8: '08:00',
  9: '09:00',
  10: '10:00',
  11: '11:00',
  12: '12:00',
  13: '13:00',
  14: '14:00',
  15: '15:00',
  16: '16:00',
  17: '17:00',
  18: '18:00',
  19: '19:00',
  20: '20:00',
  21: '21:00',
  22: '22:00',
  23: '23:00'},
 'lep': {0: 47723,
  1: 45286,
  2: 43177,
  3: 41884,
  4: 40978,
  5: 40244,
  6: 40272,
  7: 43077,
  8: 49053,
  9: 52242,
  10: 54215,
  11: 55602,
  12: 55414,
  13: 56376,
  14: 56997,
  15: 56322,
  16: 55391,
  17: 54322,
  18: 53514,
  19: 53775,
  20: 54717,
  21: 54193,
  22: 52645,
  23: 50303}}

In [28]:
# KGUP
res_kgup = eptr.call(
    "kgup",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()
res_kgup

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'time': {0: '00:00',
  1: '01:00',
  2: '02:00',
  3: '03:00',
  4: '04:00',
  5: '05:00',
  6: '06:00',
  7: '07:00',
  8: '08:00',
  9: '09:00',
  10: '10:00',
  11: '11:00',
  12: '12:00',
  13: '13:00',
  14: '14:00',
  15: '15:00',
  16: '16:00',
  17: '17:00',
  18: '18:00',
  19: '19:00',
  20: '20:00',
  21: '21:00',
  22: '22:00',
  23: '23:00'},
 'toplam': {0: 44872.96,
  1: 42236.25,
  2: 40218.84,
  3: 39095.48,
  4: 37989.67,
  5: 36950.14,
  6: 36544.8,
  7: 39172.57,
  8: 45582.14,
  9: 49727.72,
  10: 52029.39,
  11: 53329.63,
  12: 53540.21,
  13: 54231.31,
  14: 55163.4,
  15: 55728.32,
  16: 54646.34,
  17: 53410.28,
  18: 51429.91,
  19: 50557.48,
  20: 51400.4,
  21: 50878.66,
  22: 49298.43,
  23: 47368.72},
 'dogalgaz': {0: 9619.25,
  1: 8806.64,
  2: 8415.84,
  3: 8380.14,
  4: 8112.15,
  5: 7315.74,
  6: 5935.85,
  7: 5189.39,
  8: 5473.04,
  9: 5663.44,
  10: 5367.42,
  11: 5495.42,
  12: 5196.05,
  13: 5459.84,
  14: 6713.4,
  15: 7765.88,
  16: 8529.22,
  17: 10251.58,
  18: 11171.62,
  19: 11941.2,
  20: 12048.87,
  21: 11848.01,
  22: 11766.81,
  23: 10779.26},
 'ruzgar': {0: 5014.37,
  1: 4600.2,
  2: 4324.62,
  3: 4101.64,
  4: 3882.5,
  5: 3665.12,
  6: 3405.79,
  7: 3115.1,
  8: 2901.51,
  9: 2808.0,
  10: 2735.16,
  11: 2758.7,
  12: 2976.55,
  13: 3042.33,
  14: 3255.21,
  15: 3516.37,
  16: 3730.48,
  17: 4028.62,
  18: 4381.65,
  19: 4657.82,
  20: 4877.54,
  21: 4908.95,
  22: 4684.28,
  23: 4629.95},
 'linyit': {0: 4614.0,
  1: 4617.0,
  2: 4592.0,
  3: 4546.0,
  4: 4577.0,
  5: 4580.0,
  6: 4578.29,
  7: 4531.2,
  8: 4592.9,
  9: 4639.4,
  10: 4680.0,
  11: 4805.3,
  12: 4843.69,
  13: 4846.1,
  14: 4867.5,
  15: 4868.4,
  16: 4878.9,
  17: 4885.2,
  18: 4906.7,
  19: 4901.6,
  20: 4904.5,
  21: 4912.0,
  22: 4918.0,
  23: 4921.0},
 'tasKomur': {0: 269,
  1: 269,
  2: 269,
  3: 269,
  4: 269,
  5: 269,
  6: 269,
  7: 269,
  8: 269,
  9: 269,
  10: 269,
  11: 269,
  12: 269,
  13: 269,
  14: 269,
  15: 269,
  16: 269,
  17: 269,
  18: 269,
  19: 269,
  20: 269,
  21: 269,
  22: 269,
  23: 269},
 'ithalKomur': {0: 9281.5,
  1: 9279.5,
  2: 9281.5,
  3: 9224.5,
  4: 9224.5,
  5: 9224.5,
  6: 9225.5,
  7: 8983.5,
  8: 9046.5,
  9: 8852.5,
  10: 8860.5,
  11: 8881.5,
  12: 8822.5,
  13: 9096.5,
  14: 9095.5,
  15: 9187.5,
  16: 9184.5,
  17: 9170.5,
  18: 9284.5,
  19: 9281.5,
  20: 9281.5,
  21: 9281.5,
  22: 9281.5,
  23: 9281.5},
 'fuelOil': {0: 2.2,
  1: 2.2,
  2: 2.2,
  3: 2.2,
  4: 2.2,
  5: 2.2,
  6: 2.2,
  7: 2.2,
  8: 2.8,
  9: 3.6,
  10: 4.1,
  11: 4.7,
  12: 4.7,
  13: 4.2,
  14: 3.4,
  15: 2.7,
  16: 2.2,
  17: 2.2,
  18: 2.2,
  19: 2.2,
  20: 2.2,
  21: 2.2,
  22: 2.2,
  23: 2.2},
 'jeotermal': {0: 808.58,
  1: 823.7,
  2: 837.96,
  3: 852.57,
  4: 868.42,
  5: 879.33,
  6: 884.89,
  7: 880.51,
  8: 858.17,
  9: 834.02,
  10: 814.18,
  11: 785.01,
  12: 757.38,
  13: 733.45,
  14: 712.89,
  15: 697.57,
  16: 686.05,
  17: 680.7,
  18: 680.41,
  19: 692.22,
  20: 711.97,
  21: 736.43,
  22: 765.48,
  23: 783.99},
 'barajli': {0: 11826.52,
  1: 10460.15,
  2: 9233.45,
  3: 8524.45,
  4: 7862.45,
  5: 7669.95,
  6: 7309.75,
  7: 7369.74,
  8: 8654.15,
  9: 8684.87,
  10: 8595.03,
  11: 8221.77,
  12: 8225.47,
  13: 8505.19,
  14: 8934.03,
  15: 10329.25,
  16: 11508.82,
  17: 12542.82,
  18: 13563.69,
  19: 14275.97,
  20: 14975.75,
  21: 14735.25,
  22: 13759.75,
  23: 13025.75},
 'nafta': {0: 0,
  1: 0,
  2: 0,
  3: 0,
  4: 0,
  5: 0,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 0,
  16: 0,
  17: 0,
  18: 0,
  19: 0,
  20: 0,
  21: 0,
  22: 0,
  23: 0},
 'biokutle': {0: 898.69,
  1: 897.15,
  2: 896.98,
  3: 899.39,
  4: 899.44,
  5: 896.02,
  6: 899.59,
  7: 921.44,
  8: 962.3,
  9: 981.71,
  10: 989.72,
  11: 1000.43,
  12: 1003.39,
  13: 1003.96,
  14: 1002.13,
  15: 991.4,
  16: 973.02,
  17: 944.43,
  18: 921.51,
  19: 906.79,
  20: 907.28,
  21: 912.15,
  22: 911.9,
  23: 910.72},
 'akarsu': {0: 2291.92,
  1: 2233.91,
  2: 2117.54,
  3: 2044.31,
  4: 2058.85,
  5: 2081.4,
  6: 2065.16,
  7: 1781.37,
  8: 1938.03,
  9: 1982.08,
  10: 1934.98,
  11: 1882.04,
  12: 1706.96,
  13: 1831.91,
  14: 1967.01,
  15: 1815.09,
  16: 1954.89,
  17: 2171.93,
  18: 2434.37,
  19: 2738.88,
  20: 3092.61,
  21: 3011.18,
  22: 2687.08,
  23: 2513.9},
 'gunes': {0: 29.28,
  1: 29.14,
  2: 30.09,
  3: 33.62,
  4: 45.8,
  5: 185.6,
  6: 1784.43,
  7: 5948.98,
  8: 10691.61,
  9: 14805.34,
  10: 17568.99,
  11: 19013.9,
  12: 19513.99,
  13: 19218.38,
  14: 18125.41,
  15: 16048.35,
  16: 12691.62,
  17: 8237.34,
  18: 3598.22,
  19: 668.76,
  20: 109.07,
  21: 41.66,
  22: 34.8,
  23: 33.81},
 'diger': {0: 217.65,
  1: 217.66,
  2: 217.66,
  3: 217.66,
  4: 187.36,
  5: 181.28,
  6: 184.35,
  7: 180.14,
  8: 192.13,
  9: 203.76,
  10: 210.31,
  11: 211.86,
  12: 220.53,
  13: 220.45,
  14: 217.92,
  15: 236.81,
  16: 237.64,
  17: 225.96,
  18: 216.04,
  19: 221.54,
  20: 220.11,
  21: 220.33,
  22: 217.63,
  23: 217.64}}

In [29]:
# 3. PTF
eptr = EPTR2(username=username, password=password, dotenv_path=str(env_path))
res_ptf = eptr.call(
    "mcp",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()
res_ptf

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00',
  5: '2026-07-22T05:00:00+03:00',
  6: '2026-07-22T06:00:00+03:00',
  7: '2026-07-22T07:00:00+03:00',
  8: '2026-07-22T08:00:00+03:00',
  9: '2026-07-22T09:00:00+03:00',
  10: '2026-07-22T10:00:00+03:00',
  11: '2026-07-22T11:00:00+03:00',
  12: '2026-07-22T12:00:00+03:00',
  13: '2026-07-22T13:00:00+03:00',
  14: '2026-07-22T14:00:00+03:00',
  15: '2026-07-22T15:00:00+03:00',
  16: '2026-07-22T16:00:00+03:00',
  17: '2026-07-22T17:00:00+03:00',
  18: '2026-07-22T18:00:00+03:00',
  19: '2026-07-22T19:00:00+03:00',
  20: '2026-07-22T20:00:00+03:00',
  21: '2026-07-22T21:00:00+03:00',
  22: '2026-07-22T22:00:00+03:00',
  23: '2026-07-22T23:00:00+03:00'},
 'hour': {0: '00:00',
  1: '01:00',
  2: '02:00',
  3: '03:00',
  4: '04:00',
  5: '05:00',
  6: '06:00',
  7: '07:00',
  8: '08:00',
  9: '09:00',
  10: '10:00',
  11: '11:00',
  12: '12:00',
  13: '13:00',
  14: '14:00',
  15: '15:00',
  16: '16:00',
  17: '17:00',
  18: '18:00',
  19: '19:00',
  20: '20:00',
  21: '21:00',
  22: '22:00',
  23: '23:00'},
 'price': {0: 3891.45,
  1: 3602.0,
  2: 2993.0,
  3: 3449.01,
  4: 3484.15,
  5: 3555.0,
  6: 3963.5,
  7: 2117.71,
  8: 3739.15,
  9: 3795.0,
  10: 3250.0,
  11: 3449.01,
  12: 2699.0,
  13: 3300.01,
  14: 3600.0,
  15: 3083.01,
  16: 3599.99,
  17: 3900.01,
  18: 3915.27,
  19: 4499.67,
  20: 4500.0,
  21: 4500.0,
  22: 4099.99,
  23: 3600.0},
 'priceUsd': {0: 82.63,
  1: 76.49,
  2: 63.55,
  3: 73.24,
  4: 73.98,
  5: 75.49,
  6: 84.16,
  7: 44.97,
  8: 79.4,
  9: 80.58,
  10: 69.01,
  11: 73.24,
  12: 57.31,
  13: 70.07,
  14: 76.44,
  15: 65.47,
  16: 76.44,
  17: 82.81,
  18: 83.14,
  19: 95.55,
  20: 95.55,
  21: 95.55,
  22: 87.06,
  23: 76.44},
 'priceEur': {0: 72.26,
  1: 66.89,
  2: 55.58,
  3: 64.05,
  4: 64.7,
  5: 66.01,
  6: 73.6,
  7: 39.33,
  8: 69.43,
  9: 70.47,
  10: 60.35,
  11: 64.05,
  12: 50.12,
  13: 61.28,
  14: 66.85,
  15: 57.25,
  16: 66.85,
  17: 72.42,
  18: 72.71,
  19: 83.56,
  20: 83.56,
  21: 83.56,
  22: 76.14,
  23: 66.85}}

In [31]:
# 4. SMF
res_smf = eptr.call(
    "smp",
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T00:23:59+03:00"
).to_dict()

res_smf

{'date': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00'},
 'hour': {0: '2026-07-22T00:00:00+03:00',
  1: '2026-07-22T01:00:00+03:00',
  2: '2026-07-22T02:00:00+03:00',
  3: '2026-07-22T03:00:00+03:00',
  4: '2026-07-22T04:00:00+03:00'},
 'systemMarginalPrice': {0: 3891.45,
  1: 3602.0,
  2: 3450.0,
  3: 3500.0,
  4: 3902.0}}

In [ ]:
# Teklif Edilen Alış Miktarı
res_dem_offer = eptr.call(
    "dam-bid", 
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T23:59:00+03:00"
)
res_dem_offer

                         date   hour  bidQuantity
0   2026-07-22T00:00:00+03:00  00:00      29239.6
1   2026-07-22T01:00:00+03:00  01:00      28124.6
2   2026-07-22T02:00:00+03:00  02:00      27219.3
3   2026-07-22T03:00:00+03:00  03:00      26695.4
4   2026-07-22T04:00:00+03:00  04:00      26457.1
5   2026-07-22T05:00:00+03:00  05:00      26139.5
6   2026-07-22T06:00:00+03:00  06:00      26245.5
7   2026-07-22T07:00:00+03:00  07:00      25970.8
8   2026-07-22T08:00:00+03:00  08:00      29055.0
9   2026-07-22T09:00:00+03:00  09:00      30379.0
10  2026-07-22T10:00:00+03:00  10:00      30498.6
11  2026-07-22T11:00:00+03:00  11:00      30842.8
12  2026-07-22T12:00:00+03:00  12:00      29223.3
13  2026-07-22T13:00:00+03:00  13:00      30272.3
14  2026-07-22T14:00:00+03:00  14:00      31528.1
15  2026-07-22T15:00:00+03:00  15:00      32648.1
16  2026-07-22T16:00:00+03:00  16:00      33424.3
17  2026-07-22T17:00:00+03:00  17:00      34549.6
18  2026-07-22T18:00:00+03:00  18:00      34722.5
19  2026-07-22T19:00:00+03:00  19:00      35695.5
20  2026-07-22T20:00:00+03:00  20:00      35919.4
21  2026-07-22T21:00:00+03:00  21:00      35438.4
22  2026-07-22T22:00:00+03:00  22:00      32612.6
23  2026-07-22T23:00:00+03:00  23:00      31016.2

In [36]:
# Teklif Edilen Satış Miktarı
res_sup_offer = eptr.call(
    "dam-offer", 
    start_date="2026-07-22T00:00:00+03:00",
    end_date="2026-07-22T23:59:00+03:00"
)
res_sup_offer

                         date   hour  offerQuantity
0   2026-07-22T00:00:00+03:00  00:00        30647.7
1   2026-07-22T01:00:00+03:00  01:00        30086.1
2   2026-07-22T02:00:00+03:00  02:00        29972.7
3   2026-07-22T03:00:00+03:00  03:00        29585.6
4   2026-07-22T04:00:00+03:00  04:00        29220.6
5   2026-07-22T05:00:00+03:00  05:00        28916.7
6   2026-07-22T06:00:00+03:00  06:00        30188.0
7   2026-07-22T07:00:00+03:00  07:00        31771.3
8   2026-07-22T08:00:00+03:00  08:00        33501.2
9   2026-07-22T09:00:00+03:00  09:00        35284.5
10  2026-07-22T10:00:00+03:00  10:00        36013.5
11  2026-07-22T11:00:00+03:00  11:00        35083.1
12  2026-07-22T12:00:00+03:00  12:00        34565.4
13  2026-07-22T13:00:00+03:00  13:00        34577.5
14  2026-07-22T14:00:00+03:00  14:00        34780.3
15  2026-07-22T15:00:00+03:00  15:00        36109.5
16  2026-07-22T16:00:00+03:00  16:00        35778.5
17  2026-07-22T17:00:00+03:00  17:00        35449.3
18  2026-07-22T18:00:00+03:00  18:00        34780.0
19  2026-07-22T19:00:00+03:00  19:00        34185.5
20  2026-07-22T20:00:00+03:00  20:00        33312.1
21  2026-07-22T21:00:00+03:00  21:00        32580.3
22  2026-07-22T22:00:00+03:00  22:00        31997.3
23  2026-07-22T23:00:00+03:00  23:00        31694.6

In [34]:
eptr.get_available_calls()

['dam-volume',
 'pi-offer',
 'pi-bid',
 'supply-demand',
 'dam-bid',
 'dam-offer',
 'dam-block-bid',
 'dam-block-offer',
 'dam-flexible-bid',
 'dam-flexible-offer',
 'dam-flexible-matching',
 'dam-clearing',
 'dam-clearing-org-list',
 'dam-diff',
 'wap',
 'idm-qty',
 'idm-mm-bid',
 'idm-mm-offer',
 'idm-mm-matching',
 'idm-volume',
 'idm-log',
 'idm-ob-qty',
 'smp',
 'smp-dir',
 'bpm-up',
 'bpm-down',
 'bi-long',
 'bi-short',
 'bi-euas',
 'imb-qty',
 'imb-vol',
 'imb-qty-g',
 'imb-org-list',
 'mcp',
 'interim-mcp',
 'interim-mcp-status',
 'mcp-smp-imb',
 'bpm-orders-w-avg',
 'bpm-orders',
 'kgup',
 'kgup-v1',
 'kudup',
 'eak',
 'rt-gen',
 'uevm',
 'pp-list',
 'pp-list-for-date-range',
 'uevm-pp-list',
 'gen-org',
 'region-list',
 'dpp-bulk',
 'rt-gen-bulk',
 'uevcb-list-bulk',
 'mms-message-type-list',
 'mms-region-list',
 'gen-uevcb',
 'lic-pp-list',
 'long-term-demand-forecast',
 'consumer-breakdown',
 'consumption-breakdown',
 'distribution-region-list',
 'load-plan',
 'rt-cons',
 'uecm',
 'st-uecm',
 'su-uecm',
 'anc-pf-qty',
 'anc-pfk',
 'anc-sf-qty',
 'anc-sfk',
 'wind-forecast',
 'ren-pp-list',
 'ren-rt-gen',
 'ren-uevm',
 'ren-ul-gen',
 'ren-ul-cost',
 'ren-lic-cost',
 'ren-income',
 'ren-total-cost',
 'ren-capacity',
 'ren-unit-cost',
 'ren-participant-list',
 'zero-balance',
 'iskk',
 'congestion-cost',
 'eic-x-org-list',
 'eic-w-org-list',
 'eic-w-uevcb-list',
 'international-line-events',
 'tcat-pre-year-forecast',
 'tcat-pre-month-forecast',
 'line-capacities',
 'capacity-demand',
 'nominal-capacity',
 'intl-direction-list',
 'intl-capacity-demand-direction-list',
 'mms',
 'mms-pp-list',
 'mms-uevcb-list',
 'district-list',
 'profile-group-list',
 'province-list',
 'date-init',
 'market-participants',
 'market-participants-organization-list',
 'participant-count-based-upon-license-type',
 'dams-active-fullness',
 'dams-daily-level',
 'dams-active-volume',
 'dams-daily-volume',
 'basin-list',
 'dam-list',
 'dams-level-minmax',
 'dams-volume-minmax',
 'dams-info',
 'dams-water-energy-provision',
 'idm-summary',
 'electricity-market-quantity',
 'idm-contract-list',
 'idm-order-history',
 'ra-distribution-list',
 'ra-organization-list',
 'ra-spg-list',
 'ra-vspg-list',
 'ra-meters',
 'ra-meter-volumes-period',
 'ra-meter-volumes-version',
 'ra-sum',
 'ng-participants',
 'ng-participant-list',
 'ng-balancing-notifications',
 'ng-balancing-price',
 'ng-bast',
 'ng-blue-code-ops',
 'ng-daily-match-qty',
 'ng-drp',
 'ng-daily-trade-volume',
 'ng-code-four-ops',
 'ng-gddk',
 'ng-green-code-ops',
 'ng-grp-match-qty',
 'ng-grp-trade-volume',
 'ng-imbalance-amount',
 'ng-imbalance-system',
 'ng-latest-settlement-date',
 'ng-match-quantity',
 'ng-orange-code-ops',
 'ng-physical-realization',
 'ng-spot-prices',
 'ng-shippers-imbalance-quantity',
 'ng-system-direction',
 'ng-total-trade-volume',
 'ng-transaction-history',
 'ng-virtual-realization',
 'ng-weekly-matched-quantity',
 'ng-wrp',
 'ng-weekly-trade-volume',
 'ng-vgp-contract-price-summary',
 'ng-vgp-contract-price-summary-period',
 'ng-vgp-contract-price-summary-se',
 'ng-vgp-delivery-period',
 'ng-vgp-delivery-year',
 'ng-vgp-ggf',
 'ng-vgp-ggf-period',
 'ng-vgp-ggf-se',
 'ng-vgp-matched-quantity',
 'ng-vgp-matched-quantity-period',
 'ng-vgp-matched-quantity-se',
 'ng-vgp-open-positions',
 'ng-vgp-open-positions-period',
 'ng-vgp-open-positions-se',
 'ng-vgp-order-book',
 'ng-vgp-transaction-history',
 'ng-vgp-transaction-history-period',
 'ng-vgp-transaction-history-se',
 'ng-vgp-transaction-volumes',
 'ng-vgp-transaction-volumes-period',
 'ng-vgp-transaction-volumes-se',
 'ng-tr-capacity-point',
 'ng-tr-daily-transmission',
 'ng-tr-day-ahead',
 'ng-tr-day-end',
 'ng-tr-entry-nomination',
 'ng-tr-exit-nomination',
 'ng-tr-max-entry-amount',
 'ng-tr-max-exit-amount',
 'ng-tr-actual-entry-amount',
 'ng-tr-actual-exit-amount',
 'ng-tr-reserved-entry-amount',
 'ng-tr-reserved-exit-amount',
 'ng-tr-stock-amount',
 'ng-tr-storage-facility-list',
 'ng-tr-bilateral-transfer',
 'menu',
 'page-settings',
 'yek-g-bilateral-contracts',
 'yek-g-redemptions',
 'yek-g-expirations',
 'yek-g-issued',
 'yek-g-order-quantity',
 'yek-g-match-price-minmax',
 'yek-g-trade-volume',
 'yek-g-wap',
 'yek-g-withdrawals',
 'yek-g-match-quantity',
 'vep-contract-price-summary',
 'vep-delivery-period-list',
 'vep-delivery-year-list',
 'vep-ggf',
 'vep-ggf-period',
 'vep-load-types',
 'vep-price-summaries',
 'vep-open-positions',
 'vep-trade-volume',
 'vep-transaction-history',
 'vep-transaction-history-periods',
 'vep-matching-quantity',
 'eligible-consumer-count-detail',
 'eligible-consumer-quantity',
 'get-distribution-companies',
 'main-tariff-group-list',
 'monthly-index',
 'multiple-factor',
 'mf-distribution',
 'mf-meter-reading-type',
 'mf-profile-group',
 'percentage-consumption-info',
 'planned-outages',
 'elig-profile-groups',
 'eligible-consumer-count',
 'unplanned-outages']